= Введение в язык программирования Go
Бастрыков Евгений <vporoshok@gmail.com>
v0.1.0, 2020-01-31
:toc:
:source-highlighter: pygments
:stem: latexmath
:imagedir: assets/images
:github: https://github.com/vporoshok/go-introduction
:homepage: https://vporoshok.me/go-introduction/

В курсе рассматриваются базовые концепции языка Go, а также основы конкурентного программирования. Язык Go прост в изучении и при этом имеет широкие возможности для оптимизации программ, написанных на нём. В курсе также рассматриваются вопросы, не относящиеся напрямую к изучению языка, но касающиеся применения этого языка в работе или домашних проектах: соглашения по организации кода, версионирование модулей, тестирование кода и многое другое. Также курс содержит указания на материалы для факультативного изучения с более продвинутыми темами, такими как различные подходы к обработке ошибок, рефлексия, генерация кода.

Для работы с курсом вам понадобится установленный компилятор языка Go, который можно установить, воспользовавшись инструкциями на официальном сайте https://golang.org/. Также необходимо умение пользоваться командной строкой. Данный учебный материал выложен в открытом доступе под лицензией https://github.com/vporoshok/go-introduction/blob/master/LICENSE[MIT]. Исходный код находится по адресу {github}, версия для чтения — {homepage}. Если вы нашли ошибку, опечатку или неточность, откройте задачу или Pull Request в репозитории или свяжитесь со мной с помощью электронной почты vporoshok@gmail.com.

include::01-basics.adoc[]

include::02-memory.adoc[]

include::03-tests.adoc[]

include::04-oop.adoc[]

include::05-modules.adoc[]

include::06-concurrent.adoc[]

include::98-extras.adoc[]

include::99-references.adoc[]
